# Generated by Django 5.1.6 on 2025-12-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('avenue', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cause', models.CharField(choices=[('electric', 'Courant électrique'), ('cooking', 'Cuisson / bois de chauffage'), ('arson', 'Incendie criminel'), ('other', 'Autre')], default='other', max_length=20)),
                ('houses_burned', models.IntegerField(default=0)),
                ('injured', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='incidents/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.fireincident')),
            ],
        ),
    ]
