# Generated by Django 6.0 on 2025-12-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireincident',
            name='avenue',
        ),
        migrations.RemoveField(
            model_name='fireincident',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='fireincident',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='fireincident',
            name='title',
        ),
        migrations.DeleteModel(
            name='IncidentPhoto',
        ),
    ]
